### ISSUE TITLE
Materiał wyborczy KW Kandytata na Głównego Programistę Rzeczypospolitej Boomfinickiej Bartka Unxa.

### ISSUE THREAD

**Issue by Igreky** [unxcepted/unxcepted#2]
![bartekduda](https://user-images.githubusercontent.com/39243548/99988612-0cf8e980-2db2-11eb-8616-7767c9341416.png)

**Comment by Igreky** [comment]
Inspiracja:
![Augustyn](https://user-images.githubusercontent.com/39243548/99987555-e9816f00-2db0-11eb-939a-bdaa47740c6a.jpg)

**Comment by Igreky** [comment]
Zostawiam jeszcze pierwszą moją przzeróbkę Edytę Górniak
![zlazmiana](https://user-images.githubusercontent.com/39243548/99987828-349b8200-2db1-11eb-8d08-40d9dfbf32fb.png) 
![Zrzut ekranu z 2020-11-14 19-02-01](https://user-images.githubusercontent.com/39243548/99987915-4e3cc980-2db1-11eb-8d8d-aad996548b8b.png)

**Comment by unxcepted** [comment]
Ale ze pisowca ze mnie robisz
